version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kyrus_db_dev
    restart: always
    environment:
      - POSTGRES_USER=kyrus_user
      - POSTGRES_PASSWORD=kyrus_pass
      - POSTGRES_DB=kyrus_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: