"""Adiciona coluna origem em lancamentos"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0389686e6332'
down_revision: Union[str, None] = '1dd2fd1fb615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_lancamentos_origem'), 'lancamentos', ['origem'], unique=False)
    op.drop_column('lancamentos', 'loop_recorrencia')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('loop_recorrencia', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lancamentos_origem'), table_name='lancamentos')
    op.drop_column('lancamentos', 'origem')
    # ### end Alembic commands ###