"""Adiciona campo is_consultor em usuarios"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '14eee645c650'
down_revision: Union[str, None] = 'e7323297fc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona coluna como nullable primeiro
    op.add_column('usuarios', sa.Column('is_consultor', sa.Boolean(), nullable=True))
    # Atualiza todos os registros existentes para False
    op.execute("UPDATE usuarios SET is_consultor = FALSE WHERE is_consultor IS NULL")
    # Agora torna a coluna NOT NULL com default
    op.alter_column('usuarios', 'is_consultor', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_consultor')
    # ### end Alembic commands ###