"""create_pdv_tables"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1ac7c8cc8b5c'
down_revision: Union[str, None] = '818a9d12a9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdv_vendas',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('centro_custo_id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('hora_venda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rv', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_direct_sale', sa.Boolean(), nullable=False),
    sa.Column('import_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdv_vendas_centro_custo_id'), 'pdv_vendas', ['centro_custo_id'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_data_venda'), 'pdv_vendas', ['data_venda'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_empresa_id'), 'pdv_vendas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_entidade_id'), 'pdv_vendas', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_import_hash'), 'pdv_vendas', ['import_hash'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_is_deleted'), 'pdv_vendas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_rv'), 'pdv_vendas', ['rv'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_status'), 'pdv_vendas', ['status'], unique=False)
    op.create_index(op.f('ix_pdv_vendas_vendedor_id'), 'pdv_vendas', ['vendedor_id'], unique=False)
    op.create_table('pdv_movimentacoes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bandeira', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('centro_custo_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('venda_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('import_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['pdv_vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdv_movimentacoes_centro_custo_id'), 'pdv_movimentacoes', ['centro_custo_id'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_conta_id'), 'pdv_movimentacoes', ['conta_id'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_data'), 'pdv_movimentacoes', ['data'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_descricao'), 'pdv_movimentacoes', ['descricao'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_empresa_id'), 'pdv_movimentacoes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_forma_pagamento'), 'pdv_movimentacoes', ['forma_pagamento'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_import_hash'), 'pdv_movimentacoes', ['import_hash'], unique=True)
    op.create_index(op.f('ix_pdv_movimentacoes_is_deleted'), 'pdv_movimentacoes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_tipo'), 'pdv_movimentacoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_pdv_movimentacoes_venda_id'), 'pdv_movimentacoes', ['venda_id'], unique=False)
    op.create_table('pdv_venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nome_customizado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['pdv_vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdv_venda_itens_produto_id'), 'pdv_venda_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_pdv_venda_itens_venda_id'), 'pdv_venda_itens', ['venda_id'], unique=False)
    op.create_index(op.f('ix_alertas_anomalia_is_deleted'), 'alertas_anomalia', ['is_deleted'], unique=False)
    op.drop_index('ix_baixas_movimento_ofx_id', table_name='baixas')
    op.create_index(op.f('ix_baixas_movimento_id'), 'baixas', ['movimento_id'], unique=False)
    op.drop_index('idx_lancamentos_emp_pag', table_name='lancamentos')
    op.drop_index('idx_lancamentos_emp_venc', table_name='lancamentos')
    op.drop_index('idx_lancamentos_fast_bal', table_name='lancamentos', postgresql_where='((is_deleted = false) AND ((observacao IS NULL) OR (((observacao)::text !~~* \'%DestinoCompra DEMONSTRACAO%\'::text) AND ((observacao)::text !~~* \'%" legacy_id_venda\\%\'::text))))')
    op.drop_index('idx_lancamentos_no_legacy', table_name='lancamentos', postgresql_where='((is_deleted = false) AND ((observacao IS NULL) OR ((observacao)::text !~~* \'%" legacy_id_venda\\%\'::text)))')
    op.create_index(op.f('ix_lancamentos_data_pagamento'), 'lancamentos', ['data_pagamento'], unique=False)
    op.drop_index('ix_movimentos_ofx_conta_id', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_data', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_descricao', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_empresa_id', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_import_hash', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_is_deleted', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_status', table_name='movimentos')
    op.drop_index('ix_movimentos_ofx_tipo', table_name='movimentos')
    op.create_index(op.f('ix_movimentos_conta_id'), 'movimentos', ['conta_id'], unique=False)
    op.create_index(op.f('ix_movimentos_data'), 'movimentos', ['data'], unique=False)
    op.create_index(op.f('ix_movimentos_descricao'), 'movimentos', ['descricao'], unique=False)
    op.create_index(op.f('ix_movimentos_empresa_id'), 'movimentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimentos_import_hash'), 'movimentos', ['import_hash'], unique=True)
    op.create_index(op.f('ix_movimentos_is_deleted'), 'movimentos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_movimentos_origem'), 'movimentos', ['origem'], unique=False)
    op.create_index(op.f('ix_movimentos_status'), 'movimentos', ['status'], unique=False)
    op.create_index(op.f('ix_movimentos_tipo'), 'movimentos', ['tipo'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentos_tipo'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_status'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_origem'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_is_deleted'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_import_hash'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_empresa_id'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_descricao'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_data'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_conta_id'), table_name='movimentos')
    op.create_index('ix_movimentos_ofx_tipo', 'movimentos', ['tipo'], unique=False)
    op.create_index('ix_movimentos_ofx_status', 'movimentos', ['status'], unique=False)
    op.create_index('ix_movimentos_ofx_is_deleted', 'movimentos', ['is_deleted'], unique=False)
    op.create_index('ix_movimentos_ofx_import_hash', 'movimentos', ['import_hash'], unique=True)
    op.create_index('ix_movimentos_ofx_empresa_id', 'movimentos', ['empresa_id'], unique=False)
    op.create_index('ix_movimentos_ofx_descricao', 'movimentos', ['descricao'], unique=False)
    op.create_index('ix_movimentos_ofx_data', 'movimentos', ['data'], unique=False)
    op.create_index('ix_movimentos_ofx_conta_id', 'movimentos', ['conta_id'], unique=False)
    op.drop_index(op.f('ix_lancamentos_data_pagamento'), table_name='lancamentos')
    op.create_index('idx_lancamentos_no_legacy', 'lancamentos', ['empresa_id'], unique=False, postgresql_where='((is_deleted = false) AND ((observacao IS NULL) OR ((observacao)::text !~~* \'%" legacy_id_venda\\%\'::text)))')
    op.create_index('idx_lancamentos_fast_bal', 'lancamentos', ['empresa_id', 'conta_id'], unique=False, postgresql_where='((is_deleted = false) AND ((observacao IS NULL) OR (((observacao)::text !~~* \'%DestinoCompra DEMONSTRACAO%\'::text) AND ((observacao)::text !~~* \'%" legacy_id_venda\\%\'::text))))')
    op.create_index('idx_lancamentos_emp_venc', 'lancamentos', ['empresa_id', 'is_deleted', 'data_vencimento'], unique=False)
    op.create_index('idx_lancamentos_emp_pag', 'lancamentos', ['empresa_id', 'is_deleted', 'data_pagamento'], unique=False)
    op.drop_index(op.f('ix_baixas_movimento_id'), table_name='baixas')
    op.create_index('ix_baixas_movimento_ofx_id', 'baixas', ['movimento_id'], unique=False)
    op.drop_index(op.f('ix_alertas_anomalia_is_deleted'), table_name='alertas_anomalia')
    op.drop_index(op.f('ix_pdv_venda_itens_venda_id'), table_name='pdv_venda_itens')
    op.drop_index(op.f('ix_pdv_venda_itens_produto_id'), table_name='pdv_venda_itens')
    op.drop_table('pdv_venda_itens')
    op.drop_index(op.f('ix_pdv_movimentacoes_venda_id'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_tipo'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_is_deleted'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_import_hash'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_forma_pagamento'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_empresa_id'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_descricao'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_data'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_conta_id'), table_name='pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_movimentacoes_centro_custo_id'), table_name='pdv_movimentacoes')
    op.drop_table('pdv_movimentacoes')
    op.drop_index(op.f('ix_pdv_vendas_vendedor_id'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_status'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_rv'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_is_deleted'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_import_hash'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_entidade_id'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_empresa_id'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_data_venda'), table_name='pdv_vendas')
    op.drop_index(op.f('ix_pdv_vendas_centro_custo_id'), table_name='pdv_vendas')
    op.drop_table('pdv_vendas')
    # ### end Alembic commands ###