"""Adiciona tabela de centros de custo"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1dd2fd1fb615'
down_revision: Union[str, None] = '687be1494431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cartao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('limite_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dia_fechamento', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_conta_padrao', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf_cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidades_nome'), 'entidades', ['nome'], unique=False)
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_previsto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_juros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_multa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('data_competencia', sa.Date(), nullable=False),
    sa.Column('numero_parcela', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_parcelamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loop_recorrencia', sa.Boolean(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anexo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plano_contas_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('cartao_id', sa.Integer(), nullable=True),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes.id'], ),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['plano_contas_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_data_competencia'), 'lancamentos', ['data_competencia'], unique=False)
    op.create_index(op.f('ix_lancamentos_data_vencimento'), 'lancamentos', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_lancamentos_descricao'), 'lancamentos', ['descricao'], unique=False)
    op.create_index(op.f('ix_lancamentos_status'), 'lancamentos', ['status'], unique=False)
    op.create_index(op.f('ix_lancamentos_tipo'), 'lancamentos', ['tipo'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_tipo'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_status'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_descricao'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_data_vencimento'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_data_competencia'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_entidades_nome'), table_name='entidades')
    op.drop_table('entidades')
    op.drop_table('cartoes')
    # ### end Alembic commands ###