"""add_columns_to_regras_cartao"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '226b4c1e34d9'
down_revision: Union[str, None] = 'db0d83f3e4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regras_cartao', sa.Column('tipo_prazo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('regras_cartao', sa.Column('dia_fixo', sa.Integer(), nullable=True))
    op.add_column('regras_cartao', sa.Column('fds_proximo_dia_util', sa.Boolean(), nullable=False))
    op.add_column('regras_cartao', sa.Column('modo_parcelamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('regras_cartao', sa.Column('taxa_antecipacao', sa.Numeric(precision=5, scale=2), nullable=False))
    op.create_index(op.f('ix_regras_cartao_modo_parcelamento'), 'regras_cartao', ['modo_parcelamento'], unique=False)
    op.create_index(op.f('ix_regras_cartao_tipo_prazo'), 'regras_cartao', ['tipo_prazo'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regras_cartao_tipo_prazo'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_modo_parcelamento'), table_name='regras_cartao')
    op.drop_column('regras_cartao', 'taxa_antecipacao')
    op.drop_column('regras_cartao', 'modo_parcelamento')
    op.drop_column('regras_cartao', 'fds_proximo_dia_util')
    op.drop_column('regras_cartao', 'dia_fixo')
    op.drop_column('regras_cartao', 'tipo_prazo')
    # ### end Alembic commands ###