"""Add ipp"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2b3cc34b72d2'
down_revision: Union[str, None] = '95b014ff1ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('ipp', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lancamentos', 'ipp')
    # ### end Alembic commands ###