"""Add data_inicio to regras_cartao"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = '2e78abbbc5ab'
down_revision: Union[str, None] = '1ec11dec0552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regras_cartao', sa.Column('data_inicio', sa.Date(), nullable=True))
    op.create_index(op.f('ix_regras_cartao_data_inicio'), 'regras_cartao', ['data_inicio'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regras_cartao_data_inicio'), table_name='regras_cartao')
    op.drop_column('regras_cartao', 'data_inicio')
    # ### end Alembic commands ###
