"""add_nfe_compras_models"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3e2ff30e2985'
down_revision: Union[str, None] = '77240ad00b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_logs',
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_logs_created_at'), 'idempotency_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_logs_status'), 'idempotency_logs', ['status'], unique=False)
    op.create_table('fornecedor_produto_equivalencias',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('codigo_produto_fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('produto_interno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['produto_interno_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'fornecedor_id', 'codigo_produto_fornecedor', name='uq_forn_prod_equiv_empresa_forn_cod')
    )
    op.create_index(op.f('ix_fornecedor_produto_equivalencias_codigo_produto_fornecedor'), 'fornecedor_produto_equivalencias', ['codigo_produto_fornecedor'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_equivalencias_empresa_id'), 'fornecedor_produto_equivalencias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_equivalencias_fornecedor_id'), 'fornecedor_produto_equivalencias', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_equivalencias_is_deleted'), 'fornecedor_produto_equivalencias', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_equivalencias_produto_interno_id'), 'fornecedor_produto_equivalencias', ['produto_interno_id'], unique=False)
    op.add_column('produtos', sa.Column('codigo_barras', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('produtos', sa.Column('imagem_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('produtos', sa.Column('preco_custo_medio', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('ncm', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('produtos', sa.Column('cest', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('produtos', sa.Column('cfop_padrao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.drop_column('produtos', 'cfop_padrao')
    op.drop_column('produtos', 'cest')
    op.drop_column('produtos', 'ncm')
    op.drop_column('produtos', 'preco_custo_medio')
    op.drop_column('produtos', 'imagem_url')
    op.drop_column('produtos', 'codigo_barras')
    op.drop_index(op.f('ix_fornecedor_produto_equivalencias_produto_interno_id'), table_name='fornecedor_produto_equivalencias')
    op.drop_index(op.f('ix_fornecedor_produto_equivalencias_is_deleted'), table_name='fornecedor_produto_equivalencias')
    op.drop_index(op.f('ix_fornecedor_produto_equivalencias_fornecedor_id'), table_name='fornecedor_produto_equivalencias')
    op.drop_index(op.f('ix_fornecedor_produto_equivalencias_empresa_id'), table_name='fornecedor_produto_equivalencias')
    op.drop_index(op.f('ix_fornecedor_produto_equivalencias_codigo_produto_fornecedor'), table_name='fornecedor_produto_equivalencias')
    op.drop_table('fornecedor_produto_equivalencias')
    op.drop_index(op.f('ix_idempotency_logs_status'), table_name='idempotency_logs')
    op.drop_index(op.f('ix_idempotency_logs_created_at'), table_name='idempotency_logs')
    op.drop_table('idempotency_logs')
    # ### end Alembic commands ###