"""add_undone_to_audit_log"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '458dda06249c'
down_revision: Union[str, None] = 'ce63879d6324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('undone', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_baixas_is_deleted'), 'baixas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_movimentos_ofx_is_deleted'), 'movimentos_ofx', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentos_ofx_is_deleted'), table_name='movimentos_ofx')
    op.drop_index(op.f('ix_baixas_is_deleted'), table_name='baixas')
    op.drop_column('audit_logs', 'undone')
    # ### end Alembic commands ###