"""Adiciona centro_custo em cartoes"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '467366fe9bf9'
down_revision: Union[str, None] = '67d76e933a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartoes', sa.Column('centro_custo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cartoes', 'centros_custo', ['centro_custo_id'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartoes', type_='foreignkey')
    op.drop_column('cartoes', 'centro_custo_id')
    # ### end Alembic commands ###