"""Kyrus V4 Financeiro Completo"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '687be1494431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('razao_social', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cor_primaria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_nome_fantasia'), 'empresas', ['nome_fantasia'], unique=False)
    op.create_table('centros_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_custo_nome'), 'centros_custo', ['nome'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('banco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('data_saldo_inicial', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_nome'), 'contas', ['nome'], unique=False)
    op.create_index(op.f('ix_contas_tipo'), 'contas', ['tipo'], unique=False)
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permite_lancamentos', sa.Boolean(), nullable=False),
    sa.Column('conta_pai_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conta_pai_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_contas_nome'), 'plano_contas', ['nome'], unique=False)
    op.create_index(op.f('ix_plano_contas_tipo'), 'plano_contas', ['tipo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_plano_contas_tipo'), table_name='plano_contas')
    op.drop_index(op.f('ix_plano_contas_nome'), table_name='plano_contas')
    op.drop_table('plano_contas')
    op.drop_index(op.f('ix_contas_tipo'), table_name='contas')
    op.drop_index(op.f('ix_contas_nome'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_centros_custo_nome'), table_name='centros_custo')
    op.drop_table('centros_custo')
    op.drop_index(op.f('ix_empresas_nome_fantasia'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###