"""add_empresa_id_to_audit_logs"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
"""add_empresa_id_to_audit_logs"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '77240ad00b7e'
down_revision: Union[str, None] = '458dda06249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_empresa_id'), 'audit_logs', ['empresa_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill empresa_id for existing records
    # 1. lancamentos
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = l.empresa_id
        FROM lancamentos l
        WHERE al.table_name = 'lancamentos' AND al.record_id = l.id AND al.empresa_id IS NULL
    """)
    # 2. entidades
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = e.empresa_id
        FROM entidades e
        WHERE al.table_name = 'entidades' AND al.record_id = e.id AND al.empresa_id IS NULL
    """)
    # 3. contas
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = c.empresa_id
        FROM contas c
        WHERE al.table_name = 'contas' AND al.record_id = c.id AND al.empresa_id IS NULL
    """)
    # 4. usuarios
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = u.empresa_id
        FROM usuarios u
        WHERE al.table_name = 'usuarios' AND al.record_id = u.id AND al.empresa_id IS NULL
    """)
    # 5. empresas
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = al.record_id
        WHERE al.table_name = 'empresas' AND al.empresa_id IS NULL
    """)
    # 6. integracoes_bancarias
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = ib.empresa_id
        FROM integracoes_bancarias ib
        WHERE al.table_name = 'integracoes_bancarias' AND al.record_id = ib.id AND al.empresa_id IS NULL
    """)
    # 7. centros_custo
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = cc.empresa_id
        FROM centros_custo cc
        WHERE al.table_name = 'centros_custo' AND al.record_id = cc.id AND al.empresa_id IS NULL
    """)
    # 8. plano_contas
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = pc.empresa_id
        FROM plano_contas pc
        WHERE al.table_name = 'plano_contas' AND al.record_id = pc.id AND al.empresa_id IS NULL
    """)
    # 9. anexos_lancamento
    op.execute("""
        UPDATE audit_logs al
        SET empresa_id = an.empresa_id
        FROM anexos_lancamento an
        WHERE al.table_name = 'anexos_lancamento' AND al.record_id = an.id AND al.empresa_id IS NULL
    """)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_empresa_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'empresa_id')
    # ### end Alembic commands ###