"""Adiciona conta_id e centro_custo_id em integracoes_bancarias"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8763be75dfba'
down_revision: Union[str, None] = 'da3616782dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integracoes_bancarias', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.add_column('integracoes_bancarias', sa.Column('centro_custo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'integracoes_bancarias', 'centros_custo', ['centro_custo_id'], ['id'])
    op.create_foreign_key(None, 'integracoes_bancarias', 'contas', ['conta_id'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integracoes_bancarias', type_='foreignkey')
    op.drop_constraint(None, 'integracoes_bancarias', type_='foreignkey')
    op.drop_column('integracoes_bancarias', 'centro_custo_id')
    op.drop_column('integracoes_bancarias', 'conta_id')
    # ### end Alembic commands ###