"""make_pdv_fk_nullable"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8e49471286ad'
down_revision: Union[str, None] = '1ac7c8cc8b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdv_movimentacoes', 'centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pdv_movimentacoes', 'conta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pdv_vendas', 'entidade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pdv_vendas', 'vendedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pdv_vendas', 'centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdv_vendas', 'centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pdv_vendas', 'vendedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pdv_vendas', 'entidade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pdv_movimentacoes', 'conta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pdv_movimentacoes', 'centro_custo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###