"""create_orcamentos_table"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '90e2ca0bf60e'
down_revision: Union[str, None] = 'c2a1e3f7d9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plano_conta_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_orcado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='ck_orcamentos_mes_1_12'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plano_conta_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'plano_conta_id', 'ano', 'mes', name='uq_orcamentos_empresa_plano_conta_ano_mes')
    )
    op.create_index(op.f('ix_orcamentos_ano'), 'orcamentos', ['ano'], unique=False)
    op.create_index(op.f('ix_orcamentos_empresa_id'), 'orcamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_mes'), 'orcamentos', ['mes'], unique=False)
    op.create_index(op.f('ix_orcamentos_plano_conta_id'), 'orcamentos', ['plano_conta_id'], unique=False)
    op.alter_column('import_jobs', 'error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_lancamentos_ofx_bank_id'), 'lancamentos', ['ofx_bank_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_ofx_bank_id'), table_name='lancamentos')
    op.alter_column('import_jobs', 'error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_orcamentos_plano_conta_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_mes'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_empresa_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_ano'), table_name='orcamentos')
    op.drop_table('orcamentos')
    # ### end Alembic commands ###