"""Adiciona centro_custo em contas"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '95b014ff1ae6'
down_revision: Union[str, None] = '467366fe9bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('centro_custo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contas', 'centros_custo', ['centro_custo_id'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contas', type_='foreignkey')
    op.drop_column('contas', 'centro_custo_id')
    # ### end Alembic commands ###