"""add_revisao_pendente_to_produto"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cb9c5f9bf0fe'
down_revision: Union[str, None] = '00eacf1ef85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('revisao_pendente', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_produtos_revisao_pendente'), 'produtos', ['revisao_pendente'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_revisao_pendente'), table_name='produtos')
    op.drop_column('produtos', 'revisao_pendente')
    # ### end Alembic commands ###