"""create_pdv_ifood_lancamentos"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'da222fea69a9'
down_revision: Union[str, None] = '8e49471286ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdv_ifood_lancamentos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('forma_recebimento', sa.String(), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('hora_venda', sa.String(), nullable=False),
    sa.Column('data_recebimento_ajustada', sa.Date(), nullable=False),
    sa.Column('despesas_extras_str', sa.String(), nullable=True),
    sa.Column('status_conciliado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdv_ifood_lancamentos_data_recebimento_ajustada'), 'pdv_ifood_lancamentos', ['data_recebimento_ajustada'], unique=False)
    op.create_index(op.f('ix_pdv_ifood_lancamentos_data_venda'), 'pdv_ifood_lancamentos', ['data_venda'], unique=False)
    op.create_index(op.f('ix_pdv_ifood_lancamentos_empresa_id'), 'pdv_ifood_lancamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pdv_ifood_lancamentos_forma_recebimento'), 'pdv_ifood_lancamentos', ['forma_recebimento'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdv_ifood_lancamentos_forma_recebimento'), table_name='pdv_ifood_lancamentos')
    op.drop_index(op.f('ix_pdv_ifood_lancamentos_empresa_id'), table_name='pdv_ifood_lancamentos')
    op.drop_index(op.f('ix_pdv_ifood_lancamentos_data_venda'), table_name='pdv_ifood_lancamentos')
    op.drop_index(op.f('ix_pdv_ifood_lancamentos_data_recebimento_ajustada'), table_name='pdv_ifood_lancamentos')
    op.drop_table('pdv_ifood_lancamentos')
    # ### end Alembic commands ###