"""Adiciona integracoes bancarias e mapeamentos"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'da3616782dc2'
down_revision: Union[str, None] = '14eee645c650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integracoes_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ambiente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_criptografado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuracao_adicional', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('sincronizar_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('intervalo_sincronizacao_minutos', sa.Integer(), nullable=False),
    sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('proxima_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('categoria_padrao_id', sa.Integer(), nullable=True),
    sa.Column('usar_categoria_a_categorizar', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_padrao_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapeamentos_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_externa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plano_contas_id', sa.Integer(), nullable=False),
    sa.Column('integracao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integracao_id'], ['integracoes_bancarias.id'], ),
    sa.ForeignKeyConstraint(['plano_contas_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapeamentos_categoria')
    op.drop_table('integracoes_bancarias')
    # ### end Alembic commands ###