"""create_card_reconciliation_tables"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'db0d83f3e4f2'
down_revision: Union[str, None] = '5266faf2d436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regras_cartao',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bandeira', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.Column('taxa_porcentagem', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_payout', sa.Integer(), nullable=False),
    sa.Column('conta_destino_id', sa.Integer(), nullable=True),
    sa.Column('plano_contas_taxa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['conta_destino_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plano_contas_taxa_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regras_cartao_bandeira'), 'regras_cartao', ['bandeira'], unique=False)
    op.create_index(op.f('ix_regras_cartao_centro_custo_id'), 'regras_cartao', ['centro_custo_id'], unique=False)
    op.create_index(op.f('ix_regras_cartao_conta_destino_id'), 'regras_cartao', ['conta_destino_id'], unique=False)
    op.create_index(op.f('ix_regras_cartao_empresa_id'), 'regras_cartao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_regras_cartao_is_deleted'), 'regras_cartao', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_regras_cartao_plano_contas_taxa_id'), 'regras_cartao', ['plano_contas_taxa_id'], unique=False)
    op.create_index(op.f('ix_regras_cartao_tipo_pagamento'), 'regras_cartao', ['tipo_pagamento'], unique=False)
    op.create_table('lotes_cartao',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_taxa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('conta_destino_id', sa.Integer(), nullable=False),
    sa.Column('lancamento_deposito_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['conta_destino_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['lancamento_deposito_id'], ['lancamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_cartao_conta_destino_id'), 'lotes_cartao', ['conta_destino_id'], unique=False)
    op.create_index(op.f('ix_lotes_cartao_data_pagamento'), 'lotes_cartao', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_lotes_cartao_empresa_id'), 'lotes_cartao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_lotes_cartao_is_deleted'), 'lotes_cartao', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lotes_cartao_lancamento_deposito_id'), 'lotes_cartao', ['lancamento_deposito_id'], unique=False)
    op.create_index(op.f('ix_lotes_cartao_status'), 'lotes_cartao', ['status'], unique=False)
    op.create_table('lote_cartao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_cartao_id', sa.Integer(), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_taxa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['lote_cartao_id'], ['lotes_cartao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lote_cartao_itens_lancamento_id'), 'lote_cartao_itens', ['lancamento_id'], unique=False)
    op.create_index(op.f('ix_lote_cartao_itens_lote_cartao_id'), 'lote_cartao_itens', ['lote_cartao_id'], unique=False)
    op.drop_table('app_bootstrap_state')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_bootstrap_state',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='app_bootstrap_state_pkey')
    )
    op.drop_index(op.f('ix_lote_cartao_itens_lote_cartao_id'), table_name='lote_cartao_itens')
    op.drop_index(op.f('ix_lote_cartao_itens_lancamento_id'), table_name='lote_cartao_itens')
    op.drop_table('lote_cartao_itens')
    op.drop_index(op.f('ix_lotes_cartao_status'), table_name='lotes_cartao')
    op.drop_index(op.f('ix_lotes_cartao_lancamento_deposito_id'), table_name='lotes_cartao')
    op.drop_index(op.f('ix_lotes_cartao_is_deleted'), table_name='lotes_cartao')
    op.drop_index(op.f('ix_lotes_cartao_empresa_id'), table_name='lotes_cartao')
    op.drop_index(op.f('ix_lotes_cartao_data_pagamento'), table_name='lotes_cartao')
    op.drop_index(op.f('ix_lotes_cartao_conta_destino_id'), table_name='lotes_cartao')
    op.drop_table('lotes_cartao')
    op.drop_index(op.f('ix_regras_cartao_tipo_pagamento'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_plano_contas_taxa_id'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_is_deleted'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_empresa_id'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_conta_destino_id'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_centro_custo_id'), table_name='regras_cartao')
    op.drop_index(op.f('ix_regras_cartao_bandeira'), table_name='regras_cartao')
    op.drop_table('regras_cartao')
    # ### end Alembic commands ###