from __future__ import annotations

import argparse
from pathlib import Path

from app.core.config import settings


def parse_cidrs(raw_value: str | None) -> list[str]:
    if not raw_value:
        return []

    cidrs: list[str] = []
    seen: set[str] = set()
    for chunk in raw_value.replace(";", ",").replace("\n", ",").split(","):
        cidr = chunk.strip()
        if not cidr or cidr in seen:
            continue
        seen.add(cidr)
        cidrs.append(cidr)
    return cidrs


def build_hba_fragment(cidrs: list[str]) -> str:
    lines = [
        "# Generated by scripts/generate_postgres_hba.py",
        "# Include the Docker subnet used by the app container and any trusted admin CIDRs.",
    ]

    if not cidrs:
        lines.append("# POSTGRES_ALLOWED_CIDRS is empty; add at least the Docker subnet and your admin IPs.")
        return "\n".join(lines) + "\n"

    for cidr in cidrs:
        lines.append(f"host    all     all     {cidr}     scram-sha-256")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a pg_hba.conf fragment from POSTGRES_ALLOWED_CIDRS.")
    parser.add_argument("--output", type=Path, help="Write the generated fragment to a file instead of stdout.")
    args = parser.parse_args()

    fragment = build_hba_fragment(parse_cidrs(settings.POSTGRES_ALLOWED_CIDRS))

    if args.output:
        args.output.write_text(fragment, encoding="utf-8")
        print(f"pg_hba fragment written to {args.output}")
    else:
        print(fragment, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())