"""Carrega todos os modelos para registro no SQLModel.metadata."""

from app.models.empresa import Empresa
from app.models.usuario import Usuario
from app.models.consultor_empresa import ConsultorEmpresa
from app.models.access_permission import AccessPermission
from app.models.access_profile import AccessProfile
from app.models.access_profile_permission import AccessProfilePermission
from app.models.user_company_profile import UserCompanyProfile
from app.models.plano_contas import PlanoContas
from app.models.orcamento import Orcamento
from app.models.conta import Conta
from app.models.entidade import Entidade
from app.models.cartao import Cartao
from app.models.centro_custo import CentroCusto
from app.models.anexo_lancamento import AnexoLancamento
from app.models.lancamento import Lancamento
from app.models.import_job import ImportJob
from app.models.integracao_bancaria import IntegracaoBancaria
from app.models.mapeamento_categoria import MapeamentoCategoria
from app.models.plano_contas_template_config import PlanoContasTemplateConfig
from app.models.bank_preset_config import BankPresetConfig
from app.models.audit_log import AuditLog
from app.models.base_audit import AuditMixin
from app.models.todo_item import TodoItem
from app.models.produto import Produto
from app.models.fornecedor_produto_equivalencia import FornecedorProdutoEquivalencia
from app.models.movimentacao_estoque import MovimentacaoEstoque
from app.models.usuario_conta_acesso import UsuarioContaAcesso
from app.models.regra_cartao import RegraCartao
from app.models.lote_cartao import LoteCartao
from app.models.lote_cartao_item import LoteCartaoItem
from app.models.movimento import Movimento
from app.models.baixa import Baixa
from app.models.user_session import UserSession
from app.models.idempotency_log import IdempotencyLog
from app.models.regra_comissao import RegraComissao
from app.models.meta_vendedor import MetaVendedor
from app.models.alerta_anomalia import AlertaAnomalia
from app.models.regra_silenciamento_auditor import RegraSilenciamentoAuditor
from app.models.pdv_ifood_lancamento import PdvIfoodLancamento
from app.models.pdv_venda import PdvVenda
from app.models.pdv_venda_item import PdvVendaItem
from app.models.pdv_movimentacao import PdvMovimentacao
from app.models.lancamento_cartao import LancamentoCartao
from app.models.password_reset_code import PasswordResetCode
from app.models.user_invite import UserInvite


